name: DecimateCore
version: 1.0
authors: [_Ug, xTheGamerPlayz]
main: com.decimatepvp.core.DecimateCore
description: Decimate core plugin
commands:
  tntfill:
    description: Fill nearby dispensers with TNT!
  tnt:
    description: Craft TNT in your inventory!
  freeze:
    description: Freeze players.
  logout:
    description: Disconnect.
  togglechat:
    description: Toggles chat.
  spectate:
    description: Toggle spectator mode.
  colors:
    description: View colors.
  nv:
    description: Toggle night vision.
    aliases: [nightvision]
  staffchat:
    description: Toggles staff chat.
    aliases: [sc]
  harvester:
    description: Gives you the Harvester item.
  bottleexp:
    description: Bottles all the user's current exp!
    aliases: [bottle]
  who:
    description: Show online players
    aliases: [list, online]
  website:
    description: Get website link.
    aliases: [forum]
  discord:
    description: Get discord link.
  ping:
    description: View your ping
    aliases: [ms]
  blacklist:
    description: Permanently bans the player with no chance of being redeemed.
  blacklistpardon: 
    description: Removes a player from the blacklist.
  iplist:
    description: Lists players on a single IP.
  applyenchant:
    description: Applies enchant to current held item.