name: DecimateCore
version: 1.0
authors: [_Ug, xTheGamerPlayz]
main: com.decimatepvp.core.DecimateCore
description: Decimate core plugin
commands:
  tntfill:
    description: Fill nearby dispensers with TNT!
  tnt:
    description: Craft TNT in your inventory!
  freeze:
    description: Freeze players.
  logout:
    description: Disconnect.
  togglechat:
    description: Toggles chat.
  spectate:
    description: Toggle spectator mode.
  colors:
    description: View colors.
  nv:
    description: Toggle night vision.
    aliases: [nightvision]
  staffchat:
    description: Toggles staff chat.
    aliases: [sc]
  harvester:
    description: Gives you the Harvester item.
  bottleexp:
    description: Bottles all the user's current exp!
    aliases: [bottle]
  who:
    description: Show online players
    aliases: [list, online]
  website:
    description: Get website link.
    aliases: [forum]
  discord:
    description: Get discord link.
  ping:
    description: View your ping
    aliases: [ms]
  blacklist:
    description: Permanently bans the player with no chance of being redeemed.
  blacklistpardon: 
    description: Removes a player from the blacklist.
  iplist:
    description: Lists players on a single IP.
  giveenchantment:
    description: Applies enchant to current held item.
    aliases: [giveenchant]
  potionability:
    description: Gives the player a potion with a binded ability.
    aliases: [potiona, pa]
  crophopper:
    description: Gives the crop hopper
  mobhopper:
    description: Gives the mob hopper
  cratekey:
    description: Gives crate key
  boss:
    description: Summons the WitherBoss
  human:
    description: Spawns clone of player.
  store:
    description: View the server store.
    aliases: [donate]
  map:
    description: View map info.
    aliases: [season]
  dbroadcast:
    description: Broadcast to server.
  trenchpickaxe:
    description: Gives a player the Trench Pickaxe
  hub:
    description: Return to the hub.
    aliases: [lobby]
  dsellwand:
    description: Give a sellwand.
  dstop:
    description: Turn the server off.
  announcements:
    description: Toggle announcements
    aliases: [ta]
  playtime:
    description: Shows the total playtime of a player.
  trails:
    description: Open the trail selection menu
    aliases: [trail]
  trade:
    description: Allows the trade of both item and money between two players.
  war:
    description: Unknown
  sh:
    description: Sell a player head
