name: DecimateCore
version: 1.0
authors: [_Ug, xTheGamerPlayz]
main: com.decimatepvp.core.DecimateCore
description: Decimate core plugin
commands:
  tntfill:
    description: Fill nearby dispensers with TNT!
  tnt:
    description: Craft TNT in your inventory!
  freeze:
    description: Freeze players.
  logout:
    description: Disconnect.
  togglechat:
    description: Toggles chat.
  spectate:
    description: Toggle spectator mode.
<<<<<<< HEAD
  harvester:
    description: Gives wand.
  staffchat:
    description: Enable staff chat.
  colors:
    description: View colors.
  nv:
    description: Toggle night vision.
=======
  staffchat:
    description: Toggles staffchat.
  harvester:
    description: Gives you the Harvester item.
>>>>>>> origin/Random-Branch-2
 